import type { Metadata } from "next";
import "../../globals.css";
import { Providers } from "./providers";
import clsx from "clsx";
import { raleway } from "@/config/fonts";
import { Header } from "@/widgets";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={clsx(
        "min-h-screen bg-background font-sans antialiased dark",
        raleway.className
      )}
    >
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
